# Generated by Django 5.2 on 2025-04-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Zohaib Muhammad', max_length=140),
        ),
    ]
